name: General Issue
description: Please fill out the form below to submit an issue.
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Thanks for taking a minute to file an issue!**

        Read the [PSF Code of Conduct][CoC] first.

        ⚠
        Verify first that your issue is not [already reported on
        GitHub][issue search].

        _Please fill out the form below with as many precise
        details as possible._

        [CoC]: https://github.com/pypa/.github/blob/main/CODE_OF_CONDUCT.md
        [issue search]: ../search?q=is%3Aissue&type=issues

  - type: textarea
    attributes:
      label: Issue Description
      description: Please provide a detailed description of your issue.
      placeholder: Describe your issue here...
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Code of Conduct
      options:
        - label: I am aware that participants in this repository must follow the PSF Code of Conduct.
          required: true
